spring:
  application:
    name: eureka-server
server:
  port: 8010
eureka:
  instance:
    hostname: localhost #linux 修改vi /etc/hosts
    prefer-ip-address: true #改参数可以以IP形式定义注册中心，默认false不能IP
  client:
    register-with-eureka: false # 当前服务不需要到Eureka Server上注册 ,高可用的时候注册要设置成ture？
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8010/eureka/
